### ISSUE TITLE
implement correct interaction with payment service

### ISSUE THREAD

**Issue by Jumpy-Squirrel** [eurofurence/reg-payment-cncrd-adapter#26]
- Right now this service assumes that it will create the ReferenceId when requesting a paylink from Concardis. But in fact, the payment service already supplies this field, creating a payment in status tentative before calling us.
- When we are notified about a payment transaction from Concardis, we need to
  - get the correct payment by ReferenceId (it's the primary key, so no big problem)
  - update it to status pending
  Right now the payment service repository assumes we want to add a new transaction, which is wrong, unless the payment we are notified about is not found.

**Comment by tinx** [comment]
done.
